//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSdisplayer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMSdisplayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0.
        /// </summary>
        public static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8.
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 9.
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All petite caps.
        /// </summary>
        public static string AllPetiteCaps {
            get {
                return ResourceManager.GetString("AllPetiteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All small caps.
        /// </summary>
        public static string AllSmallCaps {
            get {
                return ResourceManager.GetString("AllSmallCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annotation alternates.
        /// </summary>
        public static string AnnotationAlternates {
            get {
                return ResourceManager.GetString("AnnotationAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capitals.
        /// </summary>
        public static string Capitals {
            get {
                return ResourceManager.GetString("Capitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capital spacing.
        /// </summary>
        public static string CapitalSpacing {
            get {
                return ResourceManager.GetString("CapitalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case sensitive forms.
        /// </summary>
        public static string CaseSensitiveForms {
            get {
                return ResourceManager.GetString("CaseSensitiveForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contextual alternates.
        /// </summary>
        public static string ContextualAlternates {
            get {
                return ResourceManager.GetString("ContextualAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligatures, contextual.
        /// </summary>
        public static string ContextualLigatures {
            get {
                return ResourceManager.GetString("ContextualLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swashes, contextual.
        /// </summary>
        public static string ContextualSwashes {
            get {
                return ResourceManager.GetString("ContextualSwashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1, 2, 3, 4, 5, 6, 7, 8 ,9, 0.
        /// </summary>
        public static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligatures, discretionary.
        /// </summary>
        public static string DiscretionaryLigatures {
            get {
                return ResourceManager.GetString("DiscretionaryLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à East Asian expert forms.
        /// </summary>
        public static string EastAsianExpertForms {
            get {
                return ResourceManager.GetString("EastAsianExpertForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à East Asian language.
        /// </summary>
        public static string EastAsianLanguage {
            get {
                return ResourceManager.GetString("EastAsianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à East Asian widths.
        /// </summary>
        public static string EastAsianWidths {
            get {
                return ResourceManager.GetString("EastAsianWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry, we&apos;re unable to apply your font changes..
        /// </summary>
        public static string FONT_ERROR {
            get {
                return ResourceManager.GetString("FONT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fraction.
        /// </summary>
        public static string Fraction {
            get {
                return ResourceManager.GetString("Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Half.
        /// </summary>
        public static string Half {
            get {
                return ResourceManager.GetString("Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historical forms.
        /// </summary>
        public static string HistoricalForms {
            get {
                return ResourceManager.GetString("HistoricalForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligatures, historical.
        /// </summary>
        public static string HistoricalLigatures {
            get {
                return ResourceManager.GetString("HistoricalLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hojo Kanji.
        /// </summary>
        public static string HojoKanji {
            get {
                return ResourceManager.GetString("HojoKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inferior.
        /// </summary>
        public static string Inferior {
            get {
                return ResourceManager.GetString("Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JIS-04.
        /// </summary>
        public static string Jis04 {
            get {
                return ResourceManager.GetString("Jis04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JIS-78.
        /// </summary>
        public static string Jis78 {
            get {
                return ResourceManager.GetString("Jis78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JIS-83.
        /// </summary>
        public static string Jis83 {
            get {
                return ResourceManager.GetString("Jis83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JIS-90.
        /// </summary>
        public static string Jis90 {
            get {
                return ResourceManager.GetString("Jis90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kerning.
        /// </summary>
        public static string Kerning {
            get {
                return ResourceManager.GetString("Kerning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lining.
        /// </summary>
        public static string Lining {
            get {
                return ResourceManager.GetString("Lining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mathematical Greek.
        /// </summary>
        public static string MathematicalGreek {
            get {
                return ResourceManager.GetString("MathematicalGreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NLC Kanji.
        /// </summary>
        public static string NlcKanji {
            get {
                return ResourceManager.GetString("NlcKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeral alignment.
        /// </summary>
        public static string NumeralAlignment {
            get {
                return ResourceManager.GetString("NumeralAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeral style.
        /// </summary>
        public static string NumeralStyle {
            get {
                return ResourceManager.GetString("NumeralStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old style.
        /// </summary>
        public static string OldStyle {
            get {
                return ResourceManager.GetString("OldStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1/2.
        /// </summary>
        public static string OneHalf {
            get {
                return ResourceManager.GetString("OneHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ordinal.
        /// </summary>
        public static string Ordinal {
            get {
                return ResourceManager.GetString("Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Petite caps.
        /// </summary>
        public static string PetiteCaps {
            get {
                return ResourceManager.GetString("PetiteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proportional.
        /// </summary>
        public static string Proportional {
            get {
                return ResourceManager.GetString("Proportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quarter.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ruby.
        /// </summary>
        public static string Ruby {
            get {
                return ResourceManager.GetString("Ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simplified.
        /// </summary>
        public static string Simplified {
            get {
                return ResourceManager.GetString("Simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} (simulated).
        /// </summary>
        public static string simulated {
            get {
                return ResourceManager.GetString("simulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slashed.
        /// </summary>
        public static string Slashed {
            get {
                return ResourceManager.GetString("Slashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slashed zero.
        /// </summary>
        public static string SlashedZero {
            get {
                return ResourceManager.GetString("SlashedZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Small caps.
        /// </summary>
        public static string SmallCaps {
            get {
                return ResourceManager.GetString("SmallCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stacked.
        /// </summary>
        public static string Stacked {
            get {
                return ResourceManager.GetString("Stacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligatures, standard.
        /// </summary>
        public static string StandardLigatures {
            get {
                return ResourceManager.GetString("StandardLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swashes, standard.
        /// </summary>
        public static string StandardSwashes {
            get {
                return ResourceManager.GetString("StandardSwashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic alternates.
        /// </summary>
        public static string StylisticAlternates {
            get {
                return ResourceManager.GetString("StylisticAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set  1.
        /// </summary>
        public static string StylisticSet1 {
            get {
                return ResourceManager.GetString("StylisticSet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 10.
        /// </summary>
        public static string StylisticSet10 {
            get {
                return ResourceManager.GetString("StylisticSet10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 11.
        /// </summary>
        public static string StylisticSet11 {
            get {
                return ResourceManager.GetString("StylisticSet11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 12.
        /// </summary>
        public static string StylisticSet12 {
            get {
                return ResourceManager.GetString("StylisticSet12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 13.
        /// </summary>
        public static string StylisticSet13 {
            get {
                return ResourceManager.GetString("StylisticSet13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 14.
        /// </summary>
        public static string StylisticSet14 {
            get {
                return ResourceManager.GetString("StylisticSet14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 15.
        /// </summary>
        public static string StylisticSet15 {
            get {
                return ResourceManager.GetString("StylisticSet15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 16.
        /// </summary>
        public static string StylisticSet16 {
            get {
                return ResourceManager.GetString("StylisticSet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 17.
        /// </summary>
        public static string StylisticSet17 {
            get {
                return ResourceManager.GetString("StylisticSet17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 18.
        /// </summary>
        public static string StylisticSet18 {
            get {
                return ResourceManager.GetString("StylisticSet18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 19.
        /// </summary>
        public static string StylisticSet19 {
            get {
                return ResourceManager.GetString("StylisticSet19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set  2.
        /// </summary>
        public static string StylisticSet2 {
            get {
                return ResourceManager.GetString("StylisticSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set 20.
        /// </summary>
        public static string StylisticSet20 {
            get {
                return ResourceManager.GetString("StylisticSet20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set  3.
        /// </summary>
        public static string StylisticSet3 {
            get {
                return ResourceManager.GetString("StylisticSet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set  4.
        /// </summary>
        public static string StylisticSet4 {
            get {
                return ResourceManager.GetString("StylisticSet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set  5.
        /// </summary>
        public static string StylisticSet5 {
            get {
                return ResourceManager.GetString("StylisticSet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set  6.
        /// </summary>
        public static string StylisticSet6 {
            get {
                return ResourceManager.GetString("StylisticSet6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set  7.
        /// </summary>
        public static string StylisticSet7 {
            get {
                return ResourceManager.GetString("StylisticSet7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set  8.
        /// </summary>
        public static string StylisticSet8 {
            get {
                return ResourceManager.GetString("StylisticSet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylistic set  9.
        /// </summary>
        public static string StylisticSet9 {
            get {
                return ResourceManager.GetString("StylisticSet9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscript.
        /// </summary>
        public static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Superscript.
        /// </summary>
        public static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tabular.
        /// </summary>
        public static string Tabular {
            get {
                return ResourceManager.GetString("Tabular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Third.
        /// </summary>
        public static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SMSServer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titling.
        /// </summary>
        public static string Titling {
            get {
                return ResourceManager.GetString("Titling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Traditional.
        /// </summary>
        public static string Traditional {
            get {
                return ResourceManager.GetString("Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Traditional names.
        /// </summary>
        public static string TraditionalNames {
            get {
                return ResourceManager.GetString("TraditionalNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unicase.
        /// </summary>
        public static string Unicase {
            get {
                return ResourceManager.GetString("Unicase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variants.
        /// </summary>
        public static string Variants {
            get {
                return ResourceManager.GetString("Variants", resourceCulture);
            }
        }
    }
}
